security:
    encoders:
        AppBundle\Entity\User: bcrypt
        
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        app_bundle:
            id: app.data_provider.user

    firewalls:
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            provider: app_bundle
            form_login:
                check_path: /login_check
                username_parameter: _username
                password_parameter: _password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        main:
            pattern: ^/
            provider: app_bundle
            stateless: true
            anonymous: true
            lexik_jwt: ~

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/users, roles: IS_AUTHENTICATED_ANONYMOUSLY, method: [POST] }
#        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
