services:

  # User
  AppBundle\EventListener\CreateUserListener:
    class: 'AppBundle\EventListener\CreateUserListener'
    arguments: ['@AppBundle\Service\UserPasswordHasher']
    tags:
      - { name: doctrine.event_listener, event: prePersist }
      
  AppBundle\EventListener\UpdateUserListener:
    class: 'AppBundle\EventListener\UpdateUserListener'
    arguments: ['@AppBundle\Service\UserPasswordHasher']
    tags:
      - { name: doctrine.event_listener, event: preUpdate }
      
  AppBundle\EventListener\SignInUserListener:
    class: 'AppBundle\EventListener\SignInUserListener'
    arguments: ['@doctrine.orm.default_entity_manager']
    tags:
        - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
