services:

  app.filters.range.report:
    parent: 'api_platform.doctrine.orm.range_filter'
    arguments:
      - { harassment.location.latitude: ~ , harassment.location.longitude: ~ }
    tags:  [ 'api_platform.filter' ]

  app.filters.search.report:
    parent: 'api_platform.doctrine.orm.search_filter'
    arguments:
      - { harassment.types.id: exact, reporter.id: exact }
    tags:  [ 'api_platform.filter' ]