services:

  app.filters.report.harassment_location:
    parent: 'api_platform.doctrine.orm.range_filter'
    arguments:
      - { harassment.location.latitude: ~ , harassment.location.longitude: ~ }
    tags:  [ 'api_platform.filter' ]

  app.filters.report.harassment_type:
    parent: 'api_platform.doctrine.orm.search_filter'
    arguments:
      - { harassment.types.id: exact }
    tags:  [ 'api_platform.filter' ]